// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5VY9MMATYTbVDfH5d3Kxbh6V59iv0h-k',
    appId: '1:202701566949:web:47d277deb0aa8a00d1f50c',
    messagingSenderId: '202701566949',
    projectId: 'chat-app-f7e02',
    authDomain: 'chat-app-f7e02.firebaseapp.com',
    storageBucket: 'chat-app-f7e02.appspot.com',
    measurementId: 'G-MWTL8M1LJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADpS3oO-Oj349bBkSmMudFfgihQqJkKm8',
    appId: '1:202701566949:android:089c1e2123fecad2d1f50c',
    messagingSenderId: '202701566949',
    projectId: 'chat-app-f7e02',
    storageBucket: 'chat-app-f7e02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkxUeU2XF85atmVvM8hS3pneV4sbC6cQ',
    appId: '1:202701566949:ios:2027bac482507b02d1f50c',
    messagingSenderId: '202701566949',
    projectId: 'chat-app-f7e02',
    storageBucket: 'chat-app-f7e02.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
